

---
linux:
  
  nvidia:
  
    cublasLt: nvidia/cublas/lib/libcublasLt.so.12
    cublas: nvidia/cublas/lib/libcublas.so.12
    cudnn: nvidia/cudnn/lib/libcudnn.so.9
    curand: nvidia/curand/lib/libcurand.so.10 
    cufft: nvidia/cufft/lib/libcufft.so.11
    cudart: nvidia/cuda_runtime/lib/libcudart.so.12
  
win32:
  
  nvidia:

    cublasLt: nvidia/cublas/lib/cublasLt.dll
    cublas: nvidia/cublas/lib/cublas.dll
    cudnn: nvidia/cudnn/lib/cudnn.dll
    curand: nvidia/curand/lib/curand.dll
    cufft: nvidia/cufft/lib/cufft.dll
    cudart: nvidia/cuda_runtime/lib/cudart.dll

