
# Template
# Product-type:
#   Band:
#     - "Min value"
#     - "Max value"
---
SEN2:
  B01:
    - 0    # Min
    - 1500 # Max
  B02:
    - 0
    - 1500
  B03:
    - 0
    - 1500
  B04:
    - 0
    - 1500
  B05:
    - 0
    - 1500
  B06:
    - 0
    - 1500
  B07:
    - 0
    - 1500
  B08:
    - 0
    - 1500
  B8A:
    - 0
    - 1500
  B09:
    - 0
    - 1500
  B10:
    - 0
    - 1500
  B11:
    - 0
    - 1500
  B12:
    - 0
    - 1500

SEN3:
  S1:
    - 0
    - 40
  S2:
    - 0
    - 40
  S3:
    - 0
    - 40
  S4:
    - .0
    - .1
  S5:
    - 0
    - 9
  S6:
    - 0
    - 2
  S7:
    - 0
    - 200
  S8:
    - 0
    - 200
  S9:
    - 0
    - 200
  F1:
    - 0
    - 200
  F2:
    - 0
    - 200
  LST:
    - 0
    - 200