name: pep8
run-name: flake8-run // ${{ github.actor }} // ${{ github.event_name }} // ${{ github.ref_name }}
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-flake8:
    runs-on: ubuntu-latest
    steps:
      - run: true
