name: pep8
run-name: linter // ${{ github.actor }} // ${{ github.event_name }} // ${{ github.ref_name }}
on:
  pull_request:
  push:
    branches: ["main", "development"]
    paths: ["**.py"]
  workflow_dispatch:
jobs:
  run-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
            pip install -U flake8
            flake8 src/ tests/
