name: pypi
run-name: pypi-deployment // ${{ github.actor }} // ${{ github.event_name }} // ${{ github.ref_name }}
on:
  release:
    types: ["published"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -U twine
