name: Release
run-name: PYPI-run // ${{ github.actor }} // ${{ github.event_name }} 
on:
  release:
    types: ["published"]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: true
