name: tests
run-name: tests // ${{ github.actor }} // ${{ github.event_name }} // ${{ github.ref_name }}
on:
  pull_request:
    paths: ["**.py", src/, tests/]
  push:
    branches: ["main", "development"]
    paths: ["**.py", src/, tests/]
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: verify installation
        run: |
            sudo apt-get update && sudo apt-get install gdal-bin libgdal-dev
            pip install numpy>1.0.0 wheel setuptools>=67
            pip install -U .
      - name: verify GDAL
        run: |
            python3 -c "import osgeo"
            python3 -c "import osgeo.gdal_array"
      - name: run package tests
        run: |
            python3 -m unittest -v
