name: Tests
run-name: Tests-run // ${{ github.actor }} // ${{ github.event_name }} 
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: true