name: Tests
run-name: Tests-run // ${{ github.actor }} // ${{ github.event_name }} 
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
            sudo apt-get install gdal-bin libgdal-dev python3-gdal
            pip install -U .
            python3 -c "import osgeo"
            